// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDEqn1842TraLiBZzVWj-Bcd2R5aCyL8M',
    appId: '1:1095160713979:web:ff5cf0d79f211ebb6fd65e',
    messagingSenderId: '1095160713979',
    projectId: 'bitebudget-grq2y',
    authDomain: 'bitebudget-grq2y.firebaseapp.com',
    storageBucket: 'bitebudget-grq2y.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIFghG9eJPs0-k2Q9_fL41vLB9e6XYuEA',
    appId: '1:1095160713979:android:b9c2b295bf0e53c16fd65e',
    messagingSenderId: '1095160713979',
    projectId: 'bitebudget-grq2y',
    storageBucket: 'bitebudget-grq2y.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzhJoOB38d52aHz0s1OYrHt6NOJdVVLcI',
    appId: '1:1095160713979:ios:44658a13fafcc3fa6fd65e',
    messagingSenderId: '1095160713979',
    projectId: 'bitebudget-grq2y',
    storageBucket: 'bitebudget-grq2y.firebasestorage.app',
    iosBundleId: 'com.example.bitebudget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzhJoOB38d52aHz0s1OYrHt6NOJdVVLcI',
    appId: '1:1095160713979:ios:44658a13fafcc3fa6fd65e',
    messagingSenderId: '1095160713979',
    projectId: 'bitebudget-grq2y',
    storageBucket: 'bitebudget-grq2y.firebasestorage.app',
    iosBundleId: 'com.example.bitebudget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDEqn1842TraLiBZzVWj-Bcd2R5aCyL8M',
    appId: '1:1095160713979:web:029c405f1c66034f6fd65e',
    messagingSenderId: '1095160713979',
    projectId: 'bitebudget-grq2y',
    authDomain: 'bitebudget-grq2y.firebaseapp.com',
    storageBucket: 'bitebudget-grq2y.firebasestorage.app',
  );
}
